#!/usr/bin/env python
import os, glob, os.path, codecs, logging, cgi, urllib, urllib2
from datetime import datetime

import base64
import Cookie
import email.utils
import hashlib
import hmac
import time
import wsgiref.handlers
import facebook

from django.utils import simplejson as json
from google.appengine.ext import webapp
from google.appengine.ext.webapp import util
from google.appengine.api import users
from google.appengine.ext.db import Key
from google.appengine.ext import db
from google.appengine.ext.webapp import template
from google.appengine.api import memcache
from myutil import *
#from model import Recipe, FBUser
#from recipe_dissect import ParsedRecipe
#
from google.appengine.ext import webapp
from google.appengine.ext.webapp import util

FACEBOOK_APP_ID = "138557472884201"
FACEBOOK_APP_SECRET = "d23264d3ef958891a70abec2a5d5b957"

class User()

    def __init__(self,request):
        self.nickname = None
        user = facebook.get_user_from_cookie(request.cookies, key, secret)
       if user:
         graph = facebook.GraphAPI(user["access_token"])
         self.nickname=graph["name"]
    
    def nickname(self):
        return self.nickname
    
def get_current_user(self,request):
    return User(request)
